FROM ubuntu:20.04

WORKDIR /app

RUN apt update && apt install -y wget ffmpeg \
&& wget https://github.com/bluenviron/mediamtx/releases/download/v1.15.3/mediamtx_v1.15.3_linux_amd64.tar.gz \
&& tar -xzkf mediamtx_v1.15.3_linux_amd64.tar.gz

COPY mediamtx_config.yml .

CMD sh -c './mediamtx mediamtx_config.yml '