FROM ubuntu:20.04

WORKDIR /app

ENV DEBIAN_FRONTEND=noninteractive

COPY . .

RUN apt update && apt install -y wget ffmpeg python3 python3-pip
RUN wget https://github.com/bluenviron/mediamtx/releases/download/v1.15.3/mediamtx_v1.15.3_linux_amd64.tar.gz
RUN tar -xzf mediamtx_v1.15.3_linux_amd64.tar.gz
RUN pip install --no-cache-dir -r requirements.txt
ENV PYTHONUNBUFFERED=1

CMD sh -c './mediamtx mediamtx_config.yml & sleep 2 && \
    python3 compositor.py | \
    ffmpeg \
    -f rawvideo -pix_fmt bgr24 -s 1280x720 -framerate 30 \
    -i pipe:0 \
    -c:v libx264 -pix_fmt yuv420p \
    -preset ultrafast -tune zerolatency \
    -bf 0 -g 0 \
    -x264-params "sync-lookahead=0:rc-lookahead=0" \
    -f rtsp rtsp://localhost:8554/mystream'